<span class="boldtext">How do I add the thumbnails to my posts? </span>
<div class="indent">
  <p>MyCuisine utilizes a script called TimThumb to automatically resize images. Whenever you make a new post you will need to add a custom field. Once you are on the edit/write page screen, click the "Screen Options" link on the top right of the screen and make sure "Custom Fields" is checked. Scroll down below the text editor and click on the &quot;custom fields&quot; link. In the &quot;Name&quot; section, input &quot;Thumbnail&quot; (this is case sensitive). In the &quot;Value&quot; area, input the url to your thumbnail image. Your image will automatically be resized and cropped. The image must be hosted on your domain. (this is to protect against bandwidth left) </p>
  <p><span class="style1">Important Note: You <u>must</u> CHMOD the &quot;cache&quot; folder located in the MyCuisine directory to 777 for this script to work. You can CHMOD (change the permissions) of a file using your favorite FTP program. If you are confused try following <a href="http://www.siteground.com/tutorials/ftp/ftp_chmod.htm"><u>this tutorial</u></a><u>.</u> Of course instead of CHMODing the template folder (as in the tutorial) you would CHMOD the &quot;cache&quot; folder found within your theme's directory. </span></p>
</div>
<span class="boldtext">How do I add my title/logo? </span>
<div class="indent">
In this theme the title/logo is an image, which means you will need an image editor to add your own text. You can do this by opening the blank logo image located at Photoshop Files/logo_blank.png, or by opening the logo PSD file located at Photoshop Files/logo.psd. Replace the edited logo with the old logo by placing it in the following directory: theme/MyCuisine/images, and naming the file "logo.png". If you need more room, or would like to edit the logo further, you can always do so by opening the original fully layered PSD file located at Photoshop Files/MyCuisine.psd  </div>

<span class="boldtext"> How do I manage advertisements on my blog? </span>
<div class="indent">You can change the images used in each of the advertisements, as well as which URL each ad points to, through the custom option pages found in wp-admin. Once logged in to the wordpress admin panel, click &quot;Design&quot; and then &quot;MyCuisine Theme Options&quot; to reveal the various theme options. You can also use the 125x125 advertisement widget by adding the ET: Advertisement widget to your sidebar, and filling in the required fields.  </div>

  <span class="boldtext"> How do I set up the featured slider on the homepage? </span>
  <div class="indent">
  <p>The featured slider can be set up using two different methods. You can either populate the tabs using Pages, or you can popular it using posts from a designated category. In the Appearances > MyCuisine Theme Options page in wp-admin, under the General Settings > Featured Slider tab, you will see an option that says "Use Pages." If you select this option then pages will be used, if you don't then posts will be used. If you want to use Pages then you simply select "Use Pages," and then below the option select which pages you would like to display in the slider. If you don't use pages, then simply select the "Featured Category" from the dropdown menu and posts from that category will be added to the slider. </p></div>
  
  
    <span class="boldtext"> Setting up the "Chef's Recommendations" on the Homepage. </span>
    <div class="indent">
  <p>Each of the menu items within this sections is a post taken from a specific category. The category that is used for your Chef's Recommendations can be configured from within the Appearances > MyCuisine Theme Options page under the General Settings > Homepage tab. Look for the "Exclude categories from Chef's Recommendations" section, and select (with a green checkmark) the category that you would like to use.  </p></div>
  
      <span class="boldtext"> Setting up the "Testimonials" on the Homepage. </span>
      <div class="indent">
  <p>Each testimonial is created using the Testimonial custom post type. After logging in to the WP Dashboard, look for the "Testimonials" bar on the left-hand side of your screen. Click the Testimonials > Add Testimonial link to create a new testimonials. You can create as many testimonials as you want, each of which will automatically be displayed on the homepage. Each time you load your homepage, a single (random) testimonial is chosen and displayed to your visitor. To add a photo to your testimonial, simply add the Thumbnail custom field as outlined in the "How do I add the thumbnails to my posts?" section above. </p></div>
  
        <span class="boldtext"> Setting up the "Locations" section on the Homepage. </span>
        <div class="indent">
  <p>To create the "Location" page, simply create a new page and select the "Location" page template from the Template dropdown menu on the right of the text editor. Once you have selected the Location page template, publish your page. Next you will need to input all of your location information from within the ePanel Theme Options. Click the Appearances > MyCuisine Theme Options link and navigate to the General Settings > Homepage tab.  Scroll down and fill in each field that pertains to your location, hours of operation and contact information. Once added, this information will appear on the Location page you created earlier.  </p></div>
  
 
        <span class="boldtext"> How to create a "Menu" page. </span>
  <div class="indent">
  <p>To create the "Menu" page, simply create a new page and select the "Menu" page template from the Template dropdown menu on the right of the text editor. Once you have selected the Menu page template, publish your page. Next you will need to configure which posts appear in your menu. Each "item" on the menu is a post, and each "section" of the menu is a category. You will choose which categories you would like to display in your menu, and once selected they will appear on your menu page as sections displaying their posts as menu items. To select which categories appear in your menu, click the Appearances > MyCuisine Theme Options page and navigate to the General Settings > General tab. Look for the "Exclude categories from Menu" section and select, with a green checkmark, which categories you would like to display.</p>
  <p>You will also need to define a Thumbnail Image and a Price for each "post" in your menu. This is done using custom fields. To add a thumbnail image, use the Thumbnail Custom Field as outlined in the "How do I add the thumbnails to my posts?" section above. To add a price, create a new custom field with the Name "et_price" and a Value of the price you would like to use for that post. For example, if I was create a post for a pasta dish that costs $14, then I would add the et_price custom field with a Value of "14".</p>
  </div>